import requests

# Base URL where the FastAPI IVR backend is running
BASE_URL = "http://127.0.0.1:8000"

# STEP 1: Start the IVR Call

# Send a POST request to the backend to start a new call session
response = requests.post(
    f"{BASE_URL}/ivr/start",
    json={"caller_number": "Sravanthi"}  # Caller information
)

# Convert response from JSON format to Python dictionary
data = response.json()

# Extract the session ID generated by the backend
session_id = data["session_id"]

# Print the welcome prompt returned by the IVR backend
print("System:", data["prompt"])

# STEP 2: Conversational Interaction Loop

# Start a loop to continuously accept user input
while True:

    # Get user input (simulating conversation)
    user = input("You: ")
    # CASE 1: User asks about PNR
    if "pnr" in user.lower():

        # System asks user to provide the PNR number
        print("System: Please enter your PNR number")

        # User enters the PNR number
        pnr = input("PNR: ")

        # Simulated response (in real system this would call a database or API)
        print("System: Your booking is confirmed")

        # End conversation
        break

    # CASE 2: User asks about Train Status
    elif "train" in user.lower():

        # Send a request to the IVR backend to navigate to Train Status menu
        res = requests.post(
            f"{BASE_URL}/ivr/input",
            json={
                "session_id": session_id,  # current session
                "digit": "2"                # menu option for train status
            }
        )

        # Print the response returned by the backend
        print("System:", res.json())

    # CASE 3: Unknown request
    else:

        # If the system cannot detect intent, show fallback response
        print("System: Sorry I didn't understand")
